/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Todo App API
 * Todo管理アプリケーションのAPI
 * OpenAPI spec version: 1.0.0
 */
import type { Todo } from './todo';

export type GetTodos200 = {
  items: Todo[];
  total: number;
  offset: number;
  limit: number;
};
