/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Todo App API
 * Todo管理アプリケーションのAPI
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

/**
 * 新規ユーザー登録を行う
 * @summary ユーザー登録
 */
export const signUpBodyPasswordMin = 8;

export const signUpBody = zod.object({
  email: zod.string().email(),
  password: zod.string().min(signUpBodyPasswordMin),
  name: zod.string(),
});

/**
 * メールアドレスとパスワードでサインインする
 * @summary ユーザーサインイン
 */
export const signInBody = zod.object({
  email: zod.string().email(),
  password: zod.string(),
});

export const signInResponse = zod.object({
  userId: zod.string().uuid(),
  token: zod.string(),
});
