name: Build and Publish Storybook to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
        working-directory: ./frontend
      - run: pnpm dlx msw init frontend/public/ 
        working-directory: ./frontend
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: pnpm install --prefix frontend
          build_command: pnpm --filter ./frontend build-storybook -- --output-dir=storybook-static
          path: frontend/storybook-static
          checkout: false
